import 'dart:async'; import 'dart:io'; import 'package:flutter/material.dart'; import 'package:flutter_secure_storage/flutter_secure_storage.dart'; import 'package:file_picker/file_picker.dart'; import 'package:receive_sharing_intent/receive_sharing_intent.dart'; import 'services/api.dart';
void main()=>runApp(const App());
class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext c)=>MaterialApp(title:'elizato-dl',theme:ThemeData(colorSchemeSeed:Colors.red,useMaterial3:true),home:const Shell()); }
class Shell extends StatefulWidget {const Shell({super.key});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int tab=0; final pages=[const Home(),const Queue(),const Library(),const Settings()];@override Widget build(c)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(x)=>setState(()=>tab=x),destinations:const[NavigationDestination(icon:Icon(Icons.link),label:'Home'),NavigationDestination(icon:Icon(Icons.downloading),label:'Queue'),NavigationDestination(icon:Icon(Icons.library_music),label:'Library'),NavigationDestination(icon:Icon(Icons.settings),label:'Settings')]));}
class Home extends StatefulWidget {const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{final url=TextEditingController(); File? cookies; String message='Paste a YouTube Music URL.'; StreamSubscription? share;
@override void initState(){super.initState(); share=ReceiveSharingIntent.instance.getMediaStream().listen((x){if(x.isNotEmpty)setState(()=>url.text=x.first.path);});}
Future<void> go()async{if(cookies==null){setState(()=>message='Import cookies.txt first.');return;} final s=const FlutterSecureStorage(); final base=await s.read(key:'backend')??''; final id=await s.read(key:'device')??'device-${DateTime.now().microsecondsSinceEpoch}';await s.write(key:'device',value:id);try{final p=await Api(base,id).preview(url.text,cookies!);if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>Preview(url:url.text,cookies:cookies!,playlist:p)));}catch(e){setState(()=>message='$e');}}
@override Widget build(c)=>Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Download music',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),TextField(controller:url,decoration:const InputDecoration(labelText:'Playlist or track URL')),const SizedBox(height:12),OutlinedButton(onPressed:()async{final x=await FilePicker.platform.pickFiles();if(x?.files.single.path!=null)setState(()=>cookies=File(x!.files.single.path!));},child:Text(cookies==null?'Import cookies.txt':'cookies.txt imported')),FilledButton(onPressed:go,child:const Text('Preview playlist')),Text(message)]) );}}
class Preview extends StatelessWidget{const Preview({super.key,required this.url,required this.cookies,required this.playlist});final String url;final File cookies;final Map<String,dynamic> playlist;@override Widget build(c)=>Scaffold(appBar:AppBar(title:Text(playlist['playlist_title']??'Playlist')),body:ListView(children:[...((playlist['entries']??[]) as List).map((x)=>ListTile(title:Text(x['title']??''),subtitle:Text(x['artist']??''))),Padding(padding:const EdgeInsets.all(16),child:FilledButton(onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Choose format and start job: queue wiring is next UI increment.'))),child:const Text('Download MP3')))]));}
class Queue extends StatelessWidget{const Queue({super.key});@override Widget build(c)=>const Center(child:Text('Active jobs appear here; polling continues through Android foreground service in production build.'));} class Library extends StatelessWidget{const Library({super.key});@override Widget build(c)=>const Center(child:Text('Downloaded files and player appear here.'));}
class Settings extends StatefulWidget{const Settings({super.key});@override State<Settings> createState()=>_SettingsState();}class _SettingsState extends State<Settings>{final b=TextEditingController();@override Widget build(c)=>ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:b,decoration:const InputDecoration(labelText:'HTTPS backend URL')),FilledButton(onPressed:()=>const FlutterSecureStorage().write(key:'backend',value:b.text),child:const Text('Save backend')),const Divider(),const ListTile(title:Text('Support the Developer'),subtitle:Text('BTC BEP20: 0x0cEDD7d8f78B45fbA25B05Ada32eB37F7c193590'))]);}}
